name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    env:
      DEPLOY_PATH: /home/admin/web/gescopig.com/public_html
      SSH_USER: admin
      SSH_HOST: 180.149.199.229
      SSH_PORT: 5804

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test SSH connection
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          ssh -vvv -p $SSH_PORT $SSH_USER@$SSH_HOST "echo 'SSH OK!'"
